### ISSUE TITLE
Make route configurable

### ISSUE THREAD

**Issue by sfabriece** [ziyasal/hapijs-status-monitor#11]
SInce my hapi instance has auth enabled on all routes, i had to add the config at the end to make it work. It would be nice to make it configurable, so that I can pass an option when registering the plugin.¨

``` js
server.route({
    method: 'GET',
    path: options.path,
    handler: (request, reply) => {
      const renderedHtml =
        fs.readFileSync(path.join(__dirname, '/public/index.html'))
          .toString()
          .replace(/{{title}}/g, options.title)
          .replace(/{{script}}/g, fs.readFileSync(path.join(__dirname, '/public/javascripts/app.js')))
          .replace(/{{style}}/g, fs.readFileSync(path.join(__dirname, '/public/stylesheets/style.css')));

      reply(renderedHtml)
        .header('Content-Type', 'text/html')
        .code(200)
    },
    config: {
      auth: false
    }
  })
```

**Comment by danielbayerlein** [comment]
@sfabriece Thanks for your feature request. It will be available in the next version.

**Comment by danielbayerlein** [comment]
WIP ➡️ branch `route-configurable`

**Comment by danielbayerlein** [comment]
@ziyasal What do you think about: https://github.com/ziyasal/hapijs-status-monitor/compare/route-configurable?expand=1

**Comment by sfabriece** [comment]
I would rename `options.route` to `options.routeConfig` to avoid any potential confusions. 
Otherwise everything looks good.

**Comment by ziyasal** [comment]
hey @danielbayerlein  that looks good!

**Comment by danielbayerlein** [comment]
Done, see e20172ec19a0d023af09a818e9393a8ce1bd7298
It will be available with the next version 😉

**Comment by millette** [comment]
I tried that, wanting to allow access only to logged in users, so:
```
      plugin: {
        register: 'hapijs-status-monitor',
        options: {
          title: 'Status monitor',
          path: '/status',
          // FIXME: Doesn't work, why?
          routeConfig: { auth: { mode: 'required' } }
        }
      }
```
I'm using v0.4.0. I tried in the manifest and another try in the plugin after I register an auth strategy, but I can always access /status. It might have to do with my setup (I'm not 100% sure of myself dealing with plugins and dependencies), but if someone could test that the routeConfig can actually disallow access, that would be great.

**Comment by danielbayerlein** [comment]
@millette Thanks for your feedback. v0.4.0 does not include the feature. We release a new release very soon. Sorry...

@ziyasal Can you add me to the contributors at npm?

**Comment by ziyasal** [comment]
Hi @danielbayerlein fyi, I just added.

**Comment by millette** [comment]
Doh, I should have checked the source I was using, hey ;-)

If you could also tag your git releases (```npm version patch``` instead of hand editing the version in package.json will update the version and tag it in git) that would be great!

**Comment by danielbayerlein** [comment]
@millette Sorry for the trouble. With the next version i'll also tag releases. 😺

**Comment by ziyasal** [comment]
@danielbayerlein thank you for taking over this 👍

**Comment by danielbayerlein** [comment]
hapijs-status-monitor 0.5.0 published 🎉
