### ISSUE TITLE
Add JS Linter

### ISSUE THREAD

**Issue by danielbayerlein** [ziyasal/hapijs-status-monitor#13]
We should use a style linter. For example:
* http://eslint.org (with eslint-config-airbnb-base)
* https://github.com/sindresorhus/xo
* ...

**Comment by danielbayerlein** [comment]
@ziyasal Do you prefer a style linter?

**Comment by ziyasal** [comment]
@danielbayerlein yep, i will add eslint, just forgot to add at the beginning.

**Comment by ziyasal** [comment]
or feel free to add l also prefer airbnb-base :+1:

**Comment by danielbayerlein** [comment]
@ziyasal I will add ESLint. 👍

**Comment by danielbayerlein** [comment]
WIP ➡️ https://github.com/ziyasal/hapijs-status-monitor/compare/linter

**Comment by danielbayerlein** [comment]
Done
