### ISSUE TITLE
Support multiple connections

### ISSUE THREAD

**Issue by ferrao** [ziyasal/hapijs-status-monitor#19]
When running on my project i get this error and no stats: 

```
Debug: internal, implementation, error
    TypeError: Cannot read property 'length' of undefined
    at /Users/ferrao/Dev/hapi-starter/node_modules/hapijs-status-monitor/src/helpers/on-headers-listener.js:7:47
    at Array.forEach (native)
    at module.exports.spans.forEach (/Users/ferrao/Dev/hapi-starter/node_modules/hapijs-status-monitor/src/helpers/on-headers-listener.js:6:9)
    at /Users/ferrao/Dev/hapi-starter/node_modules/hapijs-status-monitor/src/middleware-wrapper.js:43:7
    at invoke (/Users/ferrao/Dev/hapi-starter/node_modules/hapi/node_modules/podium/lib/index.js:239:30)
    at invoke (/Users/ferrao/Dev/hapi-starter/node_modules/hapi/node_modules/podium/lib/index.js:243:13)
    at Object.exports.parallel (/Users/ferrao/Dev/hapi-starter/node_modules/hapi/node_modules/items/lib/index.js:70:13)
    at Object.internals.Podium.registerEvent.internals.Podium.registerPodium.internals.emit.each [as emit] (/Users/ferrao/Dev/hapi-starter/node_modules/hapi/node_modules/podium/lib/index.js:260:18)
    at internals.Podium.registerEvent.internals.Podium.registerPodium.internals.Podium._emit (/Users/ferrao/Dev/hapi-starter/node_modules/hapi/node_modules/podium/lib/index.js:140:15)
    at internals.Podium.registerEvent.internals.Podium.registerPodium.internals.Podium.emit (/Users/ferrao/Dev/hapi-starter/node_modules/hapi/node_modules/podium/lib/index.js:113:17)
    at null.<anonymous> (/Users/ferrao/Dev/hapi-starter/node_modules/hapi/lib/response.js:701:16)
    at g (events.js:260:16)
    at emitNone (events.js:72:20)
    at emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:481:14)
    at afterWrite (_stream_writable.js:355:3)
```

**Comment by danielbayerlein** [comment]
@ferrao Which version of `hapijs-status-monitor` do you use? `master` or `0.4.0`?

**Comment by danielbayerlein** [comment]
@ferrao Can you provide your integration (plugin registration, options, ...)?

**Comment by ferrao** [comment]
@danielbayerlein, i am using `0.5.0` and this is how i am registering the plugin:

```
server.register({
        register: require('hapijs-status-monitor'),
        options: {
            title: 'My Status Monitor',
            routeConfig: {
                auth: false
            }
        }
    });
```

My server contains multiple connections, but performing `server.select().register()` does not help either.

**Comment by danielbayerlein** [comment]
@ferrao Is your example on GitHub?

**Comment by ferrao** [comment]
Yes, you can insert the registration code here https://github.com/ferrao/hapi-starter/blob/master/lib/index.js#L131

From what i see it seems you are looking for `responses` in the `spans` array, when there are none.

**Comment by danielbayerlein** [comment]
@ferrao Thank you for your feedback. I will try to fix the error.

**Comment by ferrao** [comment]
@danielbayerlein, just remember something else that might have something to do with this issue, i am using [good](https://github.com/hapijs/good) to write ops events to a file, not sure if that might interfere.

**Comment by neelmehta** [comment]
Running into the exact same issue. @danielbayerlein any ETA on fixing the issue?

**Comment by danielbayerlein** [comment]
@neelmehta We work on it. It is an open source project, built in leisure time. PR are very welcome.

**Comment by danielbayerlein** [comment]
@ziyasal Do you have any idea?

**Comment by danielbayerlein** [comment]
@ferrao / @neelmehta 

Can you please test it with the Branch `multiple-connections`? Also use the right server / connection, you can choose this with `connectionLabel`.

Add `"hapijs-status-monitor": "ziyasal/hapijs-status-monitor#multiple-connections"` to the `package.json`and `connectionLabel: 'web'` to the options.

**Comment by ferrao** [comment]
It seems to work now @danielbayerlein , but I can only use it on one connection.
If i register it on multiple connections, only the first one seems to work.

**Comment by danielbayerlein** [comment]
@ferrao Thanks for your test. Can you show me the implementation if you register hapijs-status-monitor with multiple connections? Sorry I've no experience with multiple connections.

**Comment by ziyasal** [comment]
@ferrao @danielbayerlein I will also have a look at to this, asap. Thank you for your efforts 👍

**Comment by ferrao** [comment]
Sure @danielbayerlein, there is not much to it, I am just trying to register `hapijs-status-monitor` once per connection, something like this:

```javascript
server.register([{
    register: require('hapijs-status-monitor'),
    options: {
        title: 'WebTls Status Monitor',
        connectionLabel: 'web-tls'
    }
}, {
    register: require('hapijs-status-monitor'),
    options: {
        title: 'Web Status Monitor',
        connectionLabel: 'web'
    }
}]);
```

The first registration on the array works fine, but not the second one, i.e., I only have the monitoring page available on the first connection and it only reports statistics regarding this first connection.

I would expect either to see combined statistics for all connections or to have the possibility of having a monitoring page per connection. This brings the issue that some of the data like load, cpu, mem, etc., is the same irregardless of the connection. Only the requests, responses and status data is different per connection.

This is what an ops event looks like on my setup: 

```json
{  
   "event":"ops",
   "timestamp":1482507074128,
   "host":"Ruis-MacBook-Pro-2.local",
   "pid":40603,
   "os":{  
      "load":[  
         2.2392578125,
         2.0478515625,
         1.798828125
      ],
      "mem":{  
         "total":17179869184,
         "free":3923972096
      },
      "uptime":403951
   },
   "proc":{  
      "uptime":251.691,
      "mem":{  
         "rss":98037760,
         "heapTotal":66273888,
         "heapUsed":64410720
      },
      "delay":0.259786993265152
   },
   "load":{  
      "requests":{  
         "8080":{  
            "total":0,
            "disconnects":0,
            "statusCodes":{  

            }
         },
         "8081":{  
            "total":0,
            "disconnects":0,
            "statusCodes":{  

            }
         },
         "8443":{  
            "total":0,
            "disconnects":0,
            "statusCodes":{  

            }
         }
      },
      "concurrents":{  
         "8080":0,
         "8081":1,
         "8443":1
      },
      "responseTimes":{  
         "8080":{  
            "avg":null,
            "max":0
         },
         "8081":{  
            "avg":null,
            "max":0
         },
         "8443":{  
            "avg":null,
            "max":0
         }
      },
      "sockets":{  
         "http":{  
            "total":0
         },
         "https":{  
            "total":0
         }
      }
   }
}
```

**Comment by ferrao** [comment]
Also tried `connectionLabel: ['web-tis', 'web']` but does not work at all.

**Comment by jerome724** [comment]
Any updates to this? Having the same issue.

http://i.imgur.com/ZTelwQQ.png

**Comment by danielbayerlein** [comment]
PR are very welcome!

**Comment by jimmykane** [comment]
Same here

**Comment by danielbayerlein** [comment]
I think this feature request is obsolete. With `hapi@17.0.0` multiple connections are removed, see https://github.com/hapijs/hapi/issues/3658
