### ISSUE TITLE
0.5.0 unpublished from npm?

### ISSUE THREAD

**Issue by millette** [ziyasal/hapijs-status-monitor#20]
https://libraries.io/npm/hapijs-status-monitor/versions

I'm pretty sure I used it with npm since it was released, but now it gone?

**Comment by danielbayerlein** [comment]
@millette 
```bash
$ npm view hapijs-status-monitor version
0.5.0
```

I think it's a caching problem, see https://github.com/npm/www/issues/53

**Comment by millette** [comment]
Thanks for following up. Nothing was working for me yesterday, pretty sure I was cursed.

**Comment by danielbayerlein** [comment]
https://www.npmjs.com/package/hapijs-status-monitor now displays the correct version. 🎉
