### ISSUE TITLE
Plugin crashes hapi app

### ISSUE THREAD

**Issue by kschiffer** [ziyasal/hapijs-status-monitor#21]
Hi! I'm trying to plugin the status monitor as described in the docs, but when I start my app I get this error:
```
/Users/kevinschiffer/Git/LAVAsrt/node_modules/hapijs-status-monitor/node_modules/socket.io/lib/index.js:41
  if ('object' == typeof srv && !srv.listen) {
                                    ^

TypeError: Cannot read property 'listen' of null
    at new Server (/Users/kevinschiffer/Git/LAVAsrt/node_modules/hapijs-status-monitor/node_modules/socket.io/lib/index.js:41:37)
```

Any help? I'm using hapi 16.0.1 and node 6.9.2
I would love to use this :)

**Comment by danielbayerlein** [comment]
Can you please show me the implementation?

**Comment by kschiffer** [comment]
Hi. I was able to track down the issue, and the problem was that I was running multiple connections in my hapi server but didn't select one for the plugin in my manifest. After selecting a connection, everything worked fine. But now I've got another problem I will open another issue for.
Thanks!
