### ISSUE TITLE
Support for Hapi.js 17+

### ISSUE THREAD

**Issue by ivanvs** [ziyasal/hapijs-status-monitor#24]
Firstly, I must say that you have done great job with this plugin.

I just want to ask if this plugin supports Hapi.js 17+. If not, have you considered to add support?

**Comment by bgardner87** [comment]
@ivanvs I just submitted a pull request that has this working on HapiJS 17.x.  Hopefully that works out for you :)

**Comment by danielbayerlein** [comment]
#25
