### ISSUE TITLE
1.0.0 is not on NPM

### ISSUE THREAD

**Issue by eperedo** [ziyasal/hapijs-status-monitor#26]
Hello. I am trying to use this project in my app, but just realize the latest version published to npm is the 0.6.0 and looks like that one is not v17 compatible.

I am using the master branch and it works fine, did you have considered publish the 1.0.0 to npm?

btw, the plugin looks amazing 👍

**Comment by danielbayerlein** [comment]
@eperedo Thank you for your inquiry. Unfortunately, I've not found time to test the master branch. I'm trying to release version 1.0.0 as soon as possible.

**Comment by AnnatarHe** [comment]
July, 23 2018

**Comment by bloodf** [comment]
Released?

**Comment by danielbayerlein** [comment]
Version 1.0.0 is now released
