### ISSUE TITLE
404 error haps-status-monitor

### ISSUE THREAD

**Issue by jessicabrock** [ziyasal/hapijs-status-monitor#51]
33 http fetch GET 404 https://registry.npmjs.org/@types%2fhapijs-status-monitor 390ms (cache skip)

verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@types%2fhapijs-status-monitor - Not found

verbose node v14.16.1
verbose npm  v7.21.1

**Comment by danielbayerlein** [comment]
Hi @jessicabrock,
you will find the correct package at https://www.npmjs.com/package/hapijs-status-monitor.
`hapijs-status-monitor` does not currently provide TypeScript types.
